name: food_spaces_repository
description: A repository connected with Firebase for operations related to Food Spaces.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cache:
    path: ../cache
  firebase_core: ^2.12.0
  firebase_core_platform_interface: ^4.8.0
  cloud_firestore: ^4.7.0
  shared_preferences: ^2.1.1
