name: food_control_app
description: An app for keep tracking food we have in our home
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_core: ^2.12.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  formz: ^0.6.0
  google_fonts: ^4.0.4
  intl: ^0.17.0
  meta: ^1.8.0
  authentication_repository:
    path: packages/authentication_repository
  food_spaces_repository:
    path: packages/food_spaces_repository
  accordion: ^2.5.1
  collection: ^1.17.0
  image_picker: ^1.0.2
  image_cropper: ^4.0.1
  material_design_icons_flutter: 6.0.7096
  infinite_scroll_pagination: ^3.2.0
  http: ^0.13.6
  path_provider: ^2.0.15

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/food_guardian_icon.png
