// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrxVEzC5DPhB4qLrrJi-65yBWAuYe9KJ0',
    appId: '1:502958175857:web:4bff4cf1e36a5da5224dd0',
    messagingSenderId: '502958175857',
    projectId: 'food-control-app-2023',
    authDomain: 'food-control-app-2023.firebaseapp.com',
    storageBucket: 'food-control-app-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbuckPHwijHS6OS_IuezefDbnQaEQAZxo',
    appId: '1:502958175857:android:c3726f1c5fc6f83f224dd0',
    messagingSenderId: '502958175857',
    projectId: 'food-control-app-2023',
    storageBucket: 'food-control-app-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ6rFUpeyesez6viDFSyE2thB9j1Arw7k',
    appId: '1:502958175857:ios:f394163a5539b901224dd0',
    messagingSenderId: '502958175857',
    projectId: 'food-control-app-2023',
    storageBucket: 'food-control-app-2023.appspot.com',
    iosClientId: '502958175857-273rsf5ks940cjltvjgut702bt1pf9vp.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.food-control-app',
  );
}
